version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
      python: 3.x
    commands:
      - echo "preparando el entorno..."
      - apt-get update -y
      - apt-get install -y jq

  pre_build:
    commands:
      - echo "revisando que todo el código esté en su lugar."

  build:
    commands:
      - echo "construyendo la imagen de tu aplicación con docker..."
      - cd CSS_Equipo3
      - docker build -t mi-app-financiera:latest .
      - echo "ejecutando pruebas automatizadas..."


  post_build:
    commands:
      - echo "la construcción terminó de forma exitosa."
      - echo "lista para ser desplegada en tus instancias."
