AWSTemplateFormatVersion: '2010-09-09'
Description: 'infraestructura base para soluciones tecnológicas del futuro'

Resources:
  MiVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: vpc-proyecto

  SubredPublica:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MiVPC
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true
      AvailabilityZone: us-east-1a

  GrupoSeguridadWeb:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: permite trafico http desde ips especificas
      VpcId: !Ref MiVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
  InstanciaApp:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0c7217cdde317cfec 
      NetworkInterfaces:
        - GroupSet:
            - !Ref GrupoSeguridadWeb
          AssociatePublicIpAddress: true
          DeviceIndex: '0'
          SubnetId: !Ref SubredPublica
      IamInstanceProfile: LabInstanceProfile
      Tags:
        - Key: Name
          Value: servidor-app-financiera
